SPHINXBUILD   = sphinx-build
SPHINXPROJ    = greatx
SOURCEDIR     = source
BUILDDIR      = _build

.PHONY: help Makefile

%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(0)
